version: "3.9"

services:
    flask-db:
        container_name: flask-db
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD:
            MYSQL_DATABASE:
        env_file: .env
        # volumes:
        #     - type: volume
        #       source: trio-task-db
        #       target: /var/lib/mysql
    
    flask-app:
        build: flask-app
        image: trio-task_flask-app
        environment:
            MYSQL_ROOT_PASSWORD:
            MYSQL_DATABASE:
        env_file: .env
        ports:
            - target: 5000
        deploy:
            replicas: 4
        depends_on:
            - "flask-db"

    flask-proxy:
        image: nginx:alpine
        ports:
            - target: 80
              published: 80
        volumes: 
            - type: bind
              source: ./nginx/nginx.conf
              target: /etc/nginx/nginx.conf
volumes:
    trio-task-db: